### ISSUE TITLE
TSError: _ Unable to compile TypeScript:

### ISSUE THREAD

**Issue by rag967** [damoeb/rss-proxy#1]
* Start server

cd packages/proxy && npm run start

Getting this 

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/**/*
[nodemon] watching extensions: ts
[nodemon] starting `ts-node ./src/app.ts`

/root/rss-proxy/packages/proxy/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: _ Unable to compile TypeScript:
src/endpoints/feedEndpoint.ts(5,44): error TS2307: Cannot find module '@rss-proxy/core' or its corresponding type declarations.
src/endpoints/feedEndpoint.ts(15,31): error TS2345: Argument of type 'string | ParsedQs | string[] | ParsedQs[]' is not assignable to parameter of type 'string'.
  Type 'ParsedQs' is not assignable to type 'string'.
src/endpoints/feedEndpoint.ts(35,31): error TS2345: Argument of type 'string | ParsedQs | string[] | ParsedQs[]' is not assignable to parameter of type 'string'.
  Type 'ParsedQs' is not assignable to type 'string'.

    at createTSError (/root/rss-proxy/packages/proxy/node_modules/ts-node/src/index.ts:261:12)
    at getOutput (/root/rss-proxy/packages/proxy/node_modules/ts-node/src/index.ts:367:40)
    at Object.compile (/root/rss-proxy/packages/proxy/node_modules/ts-node/src/index.ts:558:11)
    at Module.m._compile (/root/rss-proxy/packages/proxy/node_modules/ts-node/src/index.ts:439:43)
    at Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Object.require.extensions.<computed> [as .ts] (/root/rss-proxy/packages/proxy/node_modules/ts-node/src/index.ts:442:12)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by damoeb** [comment]
I will refine the docs

**Comment by krishnarag** [comment]
pls do
